### ISSUE TITLE
Crashes upon called

### ISSUE THREAD

**Issue by basile-laderchi** [vanilla-music/vanilla-music-cover-fetch#13]
- Vanilla Music Cover Fetch Version (Settings -> About): v1.4.4
- Android Version: v6.0
- Phone vendor / model: Sony Xperia XA
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

I have installed Vanilla Music v1.0.80, Cover Fetch v1.4.4, Metadata Fetch v1.0.4 and Tag Editor v1.3.0 and when I try to launch the plug-in for a specific song all I get is a message saying "Unfortunately, Vanilla Cover Fetch has stopped."

## Steps to reproduce the issue

Go to any song that and try to open the Cover Fetch plugin from the Plugins popup. I have also checked to make sure that the song had a Title, an Artist and an Album defined from the Tag Editor.

**Comment by basile-laderchi** [comment]
This is the logcat with Vanilla v1.0.81 installed (from Android Studio with "vanilla" as filter):
```
01-22 09:42:01.592 352-397/? I/BufferQueueProducer: [ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity](this:0x7f88c27800,id:35,api:1,p:9493,c:352) queueBuffer: fps=1.40 dur=12814.63 max=12561.53 min=6.37
01-22 09:42:01.666 1143-1758/? I/ActivityManager: START u0 {act=ch.blinkenlights.android.vanilla.action.LAUNCH_PLUGIN pkg=com.kanedias.vanilla.coverfetch cmp=com.kanedias.vanilla.coverfetch/.CoverShowActivity (has extras)} from uid 10332 from pid 9493 on display 0
01-22 09:42:01.688 1143-1164/? I/WindowManager: Focus moving from Window{f2a59b u0 ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity} to null
01-22 09:42:01.688 1143-1164/? I/WindowManager: Losing focus: Window{f2a59b u0 ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity}
01-22 09:42:01.694 352-399/? I/BufferQueueProducer: [ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity](this:0x7f88c27800,id:35,api:1,p:-1,c:352) disconnect(P): api 1
01-22 09:42:01.695 352-399/? I/BufferQueueConsumer: [ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity](this:0x7f88c27800,id:35,api:1,p:-1,c:352) getReleasedBuffers: returning mask 0xffffffffffffffff
01-22 09:42:01.699 352-1171/? I/BufferQueueProducer: [ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity](this:0x7f88c27800,id:35,api:1,p:-1,c:352) disconnect(P): api 1
01-22 09:42:01.720 1143-2336/? I/ActivityManager: START u0 {act=ch.blinkenlights.android.vanilla.action.LAUNCH_PLUGIN pkg=com.kanedias.vanilla.audiotag cmp=com.kanedias.vanilla.audiotag/.TagEditActivity (has extras)} from uid 10323 from pid 10692 on display 0
01-22 09:42:01.892 1143-2327/? I/ActivityManager: START u0 {act=ch.blinkenlights.android.vanilla.action.LAUNCH_PLUGIN pkg=com.kanedias.vanilla.coverfetch cmp=com.kanedias.vanilla.coverfetch/.CoverShowActivity (has extras)} from uid 10322 from pid 10680 on display 0
01-22 09:42:01.898 352-352/? I/BufferQueueConsumer: [ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity](this:0x7f88c27800,id:35,api:1,p:-1,c:-1) disconnect(C)
01-22 09:42:01.899 352-352/? I/BufferQueue: [ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity](this:0x7f88c27800,id:35,api:1,p:-1,c:-1) ~BufferQueueCore
01-22 09:42:02.067 352-352/? I/BufferQueueConsumer: [com.kanedias.vanilla.coverfetch/com.kanedias.vanilla.coverfetch.CoverShowActivity](this:0x7f88c27800,id:36,api:0,p:-1,c:352) setConsumerName: com.kanedias.vanilla.coverfetch/com.kanedias.vanilla.coverfetch.CoverShowActivity
01-22 09:42:02.067 352-352/? I/BufferQueueConsumer: [com.kanedias.vanilla.coverfetch/com.kanedias.vanilla.coverfetch.CoverShowActivity](this:0x7f88c27800,id:36,api:0,p:-1,c:352) setDefaultBufferSize: width=129 height=129
01-22 09:42:02.076 352-352/? I/BufferQueueConsumer: [com.kanedias.vanilla.coverfetch/com.kanedias.vanilla.coverfetch.CoverShowActivity](this:0x7f88c27800,id:36,api:0,p:-1,c:352) setDefaultBufferSize: width=776 height=930
01-22 09:42:02.078 1143-1164/? I/WindowManager: Focus moving from null to Window{214e55b u0 com.kanedias.vanilla.coverfetch/com.kanedias.vanilla.coverfetch.CoverShowActivity}
01-22 09:42:02.078 1143-1164/? I/WindowManager: Gaining focus: Window{214e55b u0 com.kanedias.vanilla.coverfetch/com.kanedias.vanilla.coverfetch.CoverShowActivity}
01-22 09:42:02.125 352-397/? I/BufferQueueProducer: [com.kanedias.vanilla.coverfetch/com.kanedias.vanilla.coverfetch.CoverShowActivity](this:0x7f88c27800,id:36,api:1,p:10692,c:352) connect(P): api=1 producer=(10692:com.kanedias.vanilla.coverfetch) producerControlledByApp=true
01-22 09:42:02.133 10692-10692/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kanedias.vanilla.coverfetch, PID: 10692
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.widget.ViewSwitcher.getDisplayedChild()' on a null object reference
        at com.kanedias.vanilla.coverfetch.CoverShowActivity.onPrepareOptionsMenu(CoverShowActivity.java:202)
        at android.app.Activity.onPreparePanel(Activity.java:2907)
        at com.android.internal.policy.PhoneWindow.preparePanel(PhoneWindow.java:608)
        at com.android.internal.policy.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:964)
        at com.android.internal.policy.PhoneWindow$1.run(PhoneWindow.java:284)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5763)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
01-22 09:42:02.143 1143-1153/? W/ActivityManager: Process com.kanedias.vanilla.coverfetch has crashed too many times: killing!
01-22 09:42:02.154 1143-1153/? W/ActivityManager:   Force finishing activity com.kanedias.vanilla.coverfetch/.CoverShowActivity
01-22 09:42:02.163 1143-1164/? I/WindowManager: Focus moving from Window{214e55b u0 com.kanedias.vanilla.coverfetch/com.kanedias.vanilla.coverfetch.CoverShowActivity} to Window{6db0314 u0 ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity}
01-22 09:42:02.163 1143-1164/? I/WindowManager: Gaining focus: Window{6db0314 u0 ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity}
01-22 09:42:02.163 1143-1164/? I/WindowManager: Losing focus: Window{214e55b u0 com.kanedias.vanilla.coverfetch/com.kanedias.vanilla.coverfetch.CoverShowActivity}
01-22 09:42:02.171 1143-1153/? W/ActivityManager:   Force finishing activity com.kanedias.vanilla.coverfetch/.CoverShowActivity
01-22 09:42:02.175 1143-1153/? I/ActivityManager: Killing 10692:com.kanedias.vanilla.coverfetch/u0a323 (adj 1): crash
01-22 09:42:02.176 352-1171/? I/BufferQueueProducer: [ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity](this:0x7f90f8bc00,id:27,api:1,p:9493,c:352) queueBuffer: fps=0.13 dur=15643.94 max=14966.49 min=677.45
01-22 09:42:02.293 352-399/? I/BufferQueueProducer: [com.kanedias.vanilla.coverfetch/com.kanedias.vanilla.coverfetch.CoverShowActivity](this:0x7f88c27800,id:36,api:1,p:-1,c:352) disconnect(P): api 1
01-22 09:42:02.294 352-399/? I/BufferQueueConsumer: [com.kanedias.vanilla.coverfetch/com.kanedias.vanilla.coverfetch.CoverShowActivity](this:0x7f88c27800,id:36,api:1,p:-1,c:352) getReleasedBuffers: returning mask 0xffffffffffffffff
01-22 09:42:02.298 352-352/? I/BufferQueueConsumer: [com.kanedias.vanilla.coverfetch/com.kanedias.vanilla.coverfetch.CoverShowActivity](this:0x7f88c27800,id:36,api:1,p:-1,c:-1) disconnect(C)
01-22 09:42:02.298 1143-1758/? W/ActivityManager: Spurious death for ProcessRecord{5a73095 0:com.kanedias.vanilla.coverfetch/u0a323}, curProc for 10692: null
01-22 09:42:02.298 352-352/? I/BufferQueue: [com.kanedias.vanilla.coverfetch/com.kanedias.vanilla.coverfetch.CoverShowActivity](this:0x7f88c27800,id:36,api:1,p:-1,c:-1) ~BufferQueueCore
```

This is the logcat after reinstalling Vanilla v1.0.80 installed (from Android Studio with "vanilla" as filter):
```
01-22 09:58:06.758 352-2410/? I/BufferQueueProducer: [ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity](this:0x7f88c28c00,id:148,api:1,p:12442,c:352) queueBuffer: fps=3.69 dur=5148.81 max=4889.53 min=4.78
01-22 09:58:06.780 1143-1157/? I/ActivityManager: START u0 {act=ch.blinkenlights.android.vanilla.action.LAUNCH_PLUGIN pkg=com.kanedias.vanilla.coverfetch cmp=com.kanedias.vanilla.coverfetch/.CoverShowActivity (has extras)} from uid 10340 from pid 12442 on display 0
01-22 09:58:06.791 1143-1164/? I/WindowManager: Focus moving from Window{8a3cda3 u0 ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity} to null
01-22 09:58:06.791 1143-1164/? I/WindowManager: Losing focus: Window{8a3cda3 u0 ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity}
01-22 09:58:06.795 352-397/? I/BufferQueueProducer: [ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity](this:0x7f88c28c00,id:148,api:1,p:-1,c:352) disconnect(P): api 1
01-22 09:58:06.796 352-397/? I/BufferQueueConsumer: [ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity](this:0x7f88c28c00,id:148,api:1,p:-1,c:352) getReleasedBuffers: returning mask 0xffffffffffffffff
01-22 09:58:06.803 352-1171/? I/BufferQueueProducer: [ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity](this:0x7f88c28c00,id:148,api:1,p:-1,c:352) disconnect(P): api 1
01-22 09:58:06.819 1143-1153/? I/ActivityManager: START u0 {act=ch.blinkenlights.android.vanilla.action.LAUNCH_PLUGIN pkg=com.kanedias.vanilla.audiotag cmp=com.kanedias.vanilla.audiotag/.TagEditActivity (has extras)} from uid 10323 from pid 13235 on display 0
01-22 09:58:06.879 1143-2337/? I/ActivityManager: START u0 {act=ch.blinkenlights.android.vanilla.action.LAUNCH_PLUGIN pkg=com.kanedias.vanilla.coverfetch cmp=com.kanedias.vanilla.coverfetch/.CoverShowActivity (has extras)} from uid 10322 from pid 12500 on display 0
01-22 09:58:06.997 352-352/? I/BufferQueueConsumer: [ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity](this:0x7f88c28c00,id:148,api:1,p:-1,c:-1) disconnect(C)
01-22 09:58:06.997 352-352/? I/BufferQueue: [ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity](this:0x7f88c28c00,id:148,api:1,p:-1,c:-1) ~BufferQueueCore
01-22 09:58:07.006 352-352/? I/BufferQueueConsumer: [com.kanedias.vanilla.coverfetch/com.kanedias.vanilla.coverfetch.CoverShowActivity](this:0x7f88c28c00,id:149,api:0,p:-1,c:352) setConsumerName: com.kanedias.vanilla.coverfetch/com.kanedias.vanilla.coverfetch.CoverShowActivity
01-22 09:58:07.006 352-352/? I/BufferQueueConsumer: [com.kanedias.vanilla.coverfetch/com.kanedias.vanilla.coverfetch.CoverShowActivity](this:0x7f88c28c00,id:149,api:0,p:-1,c:352) setDefaultBufferSize: width=129 height=129
01-22 09:58:07.012 352-352/? I/BufferQueueConsumer: [com.kanedias.vanilla.coverfetch/com.kanedias.vanilla.coverfetch.CoverShowActivity](this:0x7f88c28c00,id:149,api:0,p:-1,c:352) setDefaultBufferSize: width=776 height=930
01-22 09:58:07.014 1143-1164/? I/WindowManager: Focus moving from null to Window{6e26618 u0 com.kanedias.vanilla.coverfetch/com.kanedias.vanilla.coverfetch.CoverShowActivity}
01-22 09:58:07.014 1143-1164/? I/WindowManager: Gaining focus: Window{6e26618 u0 com.kanedias.vanilla.coverfetch/com.kanedias.vanilla.coverfetch.CoverShowActivity}
01-22 09:58:07.030 352-397/? I/BufferQueueProducer: [com.kanedias.vanilla.coverfetch/com.kanedias.vanilla.coverfetch.CoverShowActivity](this:0x7f88c28c00,id:149,api:1,p:13235,c:352) connect(P): api=1 producer=(13235:com.kanedias.vanilla.coverfetch) producerControlledByApp=true
01-22 09:58:07.036 13235-13235/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kanedias.vanilla.coverfetch, PID: 13235
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.widget.ViewSwitcher.getDisplayedChild()' on a null object reference
        at com.kanedias.vanilla.coverfetch.CoverShowActivity.onPrepareOptionsMenu(CoverShowActivity.java:202)
        at android.app.Activity.onPreparePanel(Activity.java:2907)
        at com.android.internal.policy.PhoneWindow.preparePanel(PhoneWindow.java:608)
        at com.android.internal.policy.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:964)
        at com.android.internal.policy.PhoneWindow$1.run(PhoneWindow.java:284)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5763)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
01-22 09:58:07.041 1143-2327/? W/ActivityManager:   Force finishing activity com.kanedias.vanilla.coverfetch/.CoverShowActivity
01-22 09:58:07.079 1143-1164/? I/WindowManager: Focus moving from Window{6e26618 u0 com.kanedias.vanilla.coverfetch/com.kanedias.vanilla.coverfetch.CoverShowActivity} to Window{8d8038d u0 Application Error: com.kanedias.vanilla.coverfetch}
01-22 09:58:07.079 1143-1164/? I/WindowManager: Gaining focus: Window{8d8038d u0 Application Error: com.kanedias.vanilla.coverfetch}
01-22 09:58:07.089 352-352/? I/BufferQueueConsumer: [Application Error: com.kanedias.vanilla.coverfetch](this:0x7f88c02000,id:150,api:0,p:-1,c:352) setConsumerName: Application Error: com.kanedias.vanilla.coverfetch
01-22 09:58:07.089 352-352/? I/BufferQueueConsumer: [Application Error: com.kanedias.vanilla.coverfetch](this:0x7f88c02000,id:150,api:0,p:-1,c:352) setDefaultBufferSize: width=129 height=129
01-22 09:58:07.100 352-352/? I/BufferQueueConsumer: [Application Error: com.kanedias.vanilla.coverfetch](this:0x7f88c02000,id:150,api:0,p:-1,c:352) setDefaultBufferSize: width=812 height=391
01-22 09:58:07.109 352-9358/? I/BufferQueueProducer: [Application Error: com.kanedias.vanilla.coverfetch](this:0x7f88c02000,id:150,api:1,p:1143,c:352) connect(P): api=1 producer=(1143:system_server) producerControlledByApp=false
01-22 09:58:07.116 352-9358/? I/BufferQueueProducer: [Application Error: com.kanedias.vanilla.coverfetch](this:0x7f88c02000,id:150,api:1,p:1143,c:352) new GraphicBuffer needed
01-22 09:58:07.137 13440-13440/? I/AEE/AED: [OnPurpose Redunant in void preset_info(aed_report_record*, int, int)] pid: 13235, tid: -1361051648, name: UNKNOWN  >>> com.kanedias.vanilla.coverfetch <<<
01-22 09:58:07.145 1143-1164/? I/WindowManager: Losing delayed focus: Window{6e26618 u0 com.kanedias.vanilla.coverfetch/com.kanedias.vanilla.coverfetch.CoverShowActivity}
01-22 09:58:07.147 352-1171/? I/BufferQueueProducer: [Application Error: com.kanedias.vanilla.coverfetch](this:0x7f88c02000,id:150,api:1,p:1143,c:352) new GraphicBuffer needed
01-22 09:58:07.543 1143-1159/? W/ActivityManager: Activity pause timeout for ActivityRecord{ac4b700 u0 com.kanedias.vanilla.coverfetch/.CoverShowActivity t10 f}
01-22 09:58:07.569 352-1171/? I/BufferQueueProducer: [ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity](this:0x7f88c47000,id:146,api:1,p:12442,c:352) queueBuffer: fps=0.26 dur=7619.73 max=7475.40 min=144.33
01-22 09:58:08.065 352-2410/? I/BufferQueueProducer: [Application Error: com.kanedias.vanilla.coverfetch](this:0x7f88c02000,id:150,api:1,p:1143,c:352) new GraphicBuffer needed
01-22 09:58:08.702 352-2410/? I/BufferQueueProducer: [Application Error: com.kanedias.vanilla.coverfetch](this:0x7f88c02000,id:150,api:1,p:1143,c:352) new GraphicBuffer needed
01-22 09:58:08.706 352-1171/? I/BufferQueueProducer: [Application Error: com.kanedias.vanilla.coverfetch](this:0x7f88c02000,id:150,api:1,p:1143,c:352) queueBuffer: fps=1.92 dur=1564.54 max=916.51 min=10.94
```

**Comment by Kaned1as** [comment]
Wait for 1.4.5 in F-Droid or try release build from Releases page.

**Comment by basile-laderchi** [comment]
Just installed v1.4.5 from the Releases page and it's working just great.
